
sp:
  entity-id: https://qa.test.swedenconnect.se/testmyeid
  sign-entity-id: http://qa.swedenconnect.se/testmyeid-sign
  eidas-connector:
    entity-id: https://qa.connector.eidas.swedenconnect.se/eidas  
  discovery:
    ignore-contracts: true
    include-only-static: true
    static-idp-configuration: classpath:qa/idp-disco-qa.yml
  federation:
    metadata:
      url: https://qa.md.swedenconnect.se/role/idp.xml
      validation-certificate: classpath:qa/sc-qa-metadata.crt
  security:
    algorithm-config:
      use-aes-gcm: true
      
logging:
  level:
    root: WARN
    testmyeid: INFO
