#
# Main configuration of the Test my eID-application
#

info:
  app:
    description: Application for testing my eID
    name: test-my-eid
    version: '@project.version@'

#
# Server settings
#
server:
  port: 8443
  servlet:
    context-path: /testmyeid
    session:
      cookie:
        http-only: true
        same-site: none
        secure: true
  ssl:
    enabled: true
    key-alias: localhost
    key-password: secret
    key-store: classpath:snakeoil-localhost.p12
    key-store-password: secret
    key-store-type: PKCS12
    
#
# Management
#   
management:
  server:
    base-path: ${server.servlet.context-path}
    port: 8444
    ssl:
      enabled: ${server.ssl.enabled}
      key-alias: ${server.ssl.key-alias}
      key-password: ${server.ssl.key-password}
      key-store: ${server.ssl.key-store}
      key-store-password: ${server.ssl.key-store-password}
      key-store-type: ${server.ssl.key-store-type}    
  endpoint:
    health:
      status:
        order:
        - DOWN
        - OUT_OF_SERVICE
        - UP
        - WARNING
        - UNKNOWN
        http-mapping:
          WARNING: 500
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
    
logging:
  level:
    testmyeid: DEBUG
    root: INFO
    se:
      swedenconnect: ${logging.level.testmyeid}    
    

sign-sp:
  entity-id: http://test.swedenconnect.se/testmyeid-sign
  
sp:
  base-uri: https://localhost:${server.port}
  entity-id: http://test.swedenconnect.se/testmyeid
  credential:
    sign:
      alias: sign
      resource: classpath:sp-keys.jks
      key-password: secret
      password: secret
      type: JKS  
    decrypt:
      alias: encrypt
      resource: classpath:sp-keys.jks
      key-password: secret
      password: secret
      type: JKS
    md-sign:
      alias: mdsign
      resource: classpath:metadata-sign.jks
      key-password: secret
      password: secret
      type: JKS
  discovery:
    cache-time: 600
    ignore-contracts: true
    include-only-static: false
  metadata:
    entity-categories:
    - http://id.elegnamnden.se/ec/1.0/loa3-pnr
    - http://id.swedenconnect.se/ec/sc/uncertified-loa3-pnr
    - http://id.elegnamnden.se/ec/1.0/loa4-pnr
    - http://id.elegnamnden.se/ec/1.0/eidas-naturalperson
    - http://id.swedenconnect.se/ec/1.0/loa3-orgid
    - http://id.swedenconnect.se/ec/1.0/loa4-orgid
    - http://id.elegnamnden.se/st/1.0/public-sector-sp
    - http://id.swedenconnect.se/contract/sc/sweden-connect
    - http://id.swedenconnect.se/contract/sc/eid-choice-2017
    - http://id.swedenconnect.se/contract/sc/prepaid-auth-2021
    - http://id.swedenconnect.se/general-ec/1.0/secure-authenticator-binding
    - http://id.swedenconnect.se/general-ec/1.0/accepts-coordination-number
    uiinfo:
      display-names:
      - sv-Testa mitt eID
      - en-Test my eID    
      descriptions:
      - sv-Applikation för att testa ditt eID
      - en-Application for testing your eID
      logos:
      - height: 56
        path: /images/logo.svg
        width: 280
      - height: 256
        path: /images/logo-notext.svg
        width: 256    
    requested-attributes:
    - name: urn:oid:0.9.2342.19200300.100.1.3
      required: false
    - name: urn:oid:0.9.2342.19200300.100.1.41
      required: false
    service-names:
    - sv-Testa ditt eID
    - en-Test your eID    
    contact-persons:
      support:
        company: Sweden Connect
        email-address: operations@swedenconnect.se
      technical:
        company: Sweden Connect
        email-address: operations@swedenconnect.se    
    organization:
      display-names:
      - sv-Sweden Connect
      - en-Sweden Connect
      names:
      - sv-Sweden Connect
      - en-Sweden Connect
      urls:
      - sv-https://swedenconnect.se
      - en-https://swedenconnect.se
  mtls:
    header-name: SSL_CLIENT_CERT
  security:
    algorithm-config:
      blacklist-rsa15: true
      use-aes-gcm: true
  ui:
    lang:
    - language-tag: sv
      text: Svenska
    - language-tag: en
      text: English  
    attributes:
    - attribute-name: urn:oid:1.2.752.29.4.13      
      message-code: sp.msg.attr.personal-id-number.name
      description-message-code-eidas: sp.msg.attr.personal-id-number.eidas.desc
      message-code-eidas: sp.msg.attr.personal-id-number.eidas.name
    - attribute-name: urn:oid:1.2.752.201.3.16
      message-code: sp.msg.attr.personal-id-number.name
      message-code-eidas: sp.msg.attr.personal-id-number.eidas.name
      description-message-code-eidas: sp.msg.attr.personal-id-number.eidas.desc      
    - attribute-name: urn:oid:1.2.752.201.3.4
      message-code: sp.msg.attr.prid.name
      description-message-code-eidas: sp.msg.attr.prid.eidas.desc      
    - attribute-name: urn:oid:1.2.752.201.3.1
      message-code: sp.msg.attr.org-affiliation.name
      description-message-code: sp.msg.attr.org-affiliation.desc      
    - attribute-name: urn:oid:2.5.4.42
      message-code: sp.msg.attr.given-name.name
    - attribute-name: urn:oid:2.5.4.4
      message-code: sp.msg.attr.surname.name
    - attribute-name: urn:oid:1.3.6.1.5.5.7.9.1
      message-code: sp.msg.attr.date-of-birth.name
    - attribute-name: urn:oid:2.16.840.1.113730.3.1.241
      message-code: sp.msg.attr.display-name.name
    - attribute-name: urn:oid:2.5.4.6
      message-code: sp.msg.attr.c.name
      description-message-code-eidas: sp.msg.attr.c.eidas.desc      
    - attribute-name: urn:oid:1.2.752.201.3.8
      message-code: sp.msg.attr.birth-name.name
      description-message-code-eidas: sp.msg.attr.birth-name.eidas.desc      
    - attribute-name: urn:oid:1.3.6.1.5.5.7.9.2
      message-code: sp.msg.attr.place-of-birth.name
    - attribute-name: urn:oid:1.3.6.1.5.5.7.9.3
      message-code: sp.msg.attr.gender.name
      description-message-code: sp.msg.attr.gender.desc
      description-message-code-eidas: sp.msg.attr.gender.eidas.desc      
    - attribute-name: urn:oid:1.2.752.201.3.7
      message-code: sp.msg.attr.eidas-id.name
      description-message-code-eidas: sp.msg.attr.eidas-id.eidas.desc      
      advanced: true
    - attribute-name: urn:oid:1.2.752.201.3.5
      message-code: sp.msg.attr.prid-persistence.name
      description-message-code-eidas: sp.msg.attr.prid-persistence.eidas.desc      
      advanced: true
    - attribute-name: urn:oid:1.2.752.201.3.2
      message-code: sp.msg.attr.transaction-identifier.name
      description-message-code: sp.msg.attr.transaction-identifier.desc
      description-message-code-eidas: sp.msg.attr.transaction-identifier.eidas.desc      
      advanced: true
    - attribute-name: urn:oid:1.2.752.201.3.6
      message-code: sp.msg.attr.personal-id-number-binding.name
      description-message-code-eidas: sp.msg.attr.personal-id-number-binding.eidas.desc      
      advanced: true
    - attribute-name: urn:oid:1.2.752.201.3.14
      message-code: sp.msg.attr.sign-message-digest.name
      description-message-code: sp.msg.attr.sign-message-digest.desc      
      advanced: true
    - attribute-name: urn:oid:0.9.2342.19200300.100.1.3
      message-code: sp.msg.attr.email.name
      description-message-code: sp.msg.attr.email.desc      
    - attribute-name: urn:oid:0.9.2342.19200300.100.1.41
      message-code: sp.msg.attr.mobile.name
      description-message-code: sp.msg.attr.mobile.desc      
    - attribute-name: urn:oid:2.5.4.97
      message-code: sp.msg.attr.orgid.name
      description-message-code: sp.msg.attr.orgid.desc      
    - attribute-name: urn:oid:2.5.4.10
      message-code: sp.msg.attr.organization.name
      
