server:
  servlet:
    session:
      cookie:
        domain: idsec.se

tomcat:
  ajp:
    enabled: true
    port: 8009
    secret-required: false

sp:
  base-uri: https://eid.idsec.se
  hok-base-uri: https://hok.idsec.se
  entity-id: http://sandbox.swedenconnect.se/testmyeid
  sign-entity-id: http://sandbox.swedenconnect.se/testmyeid-sign 
  discovery:
    include-only-static: true
    static-idp-configuration: classpath:sandbox/idp-disco-sandbox.yml
  eidas-connector:
    entity-id: https://dev.connector.swedenconnect.se/eidas
  federation:
    metadata:
      url: https://eid.svelegtest.se/metadata/mdx/role/idp.xml
      validation-certificate: classpath:sandbox/sandbox-metadata.crt
    
logging:
  level:
    se:
      swedenconnect:
        eid:
          sp:
            config: WARN
        opensaml:
          saml2:
            response: TRACE
          sweid:
              saml2:
                discovery: WARN
